const lessons=[
[1,'Приветствия','Базовые приветствия и знакомство','👋'],[2,'Числа и счёт','Числа, количество и dvojina','🔢'],[3,'Семья','Родственные связи','👨‍👩‍👧'],[4,'Еда и напитки','Повседневная лексика','🥐'],[5,'Дни недели и месяцы','Календарь и даты','📅'],[6,'Глагол biti и о себе','Кто мы и откуда','🙋'],[7,'Глагол imeti','Обладание','🎒'],[8,'Цвета и прилагательные','Согласование по роду','🎨'],[9,'Дом и предметы','Бытовая лексика','🏠'],[10,'Вопросительные слова','kaj / kdo / kje / kdaj / zakaj','❓'],[11,'biti — все формы','Настоящее, dvojina, l-причастие','🧬'],[12,'imeti — все формы','Полная парадигма','🧰'],[13,'hoteti — хотеть','Формы во всех числах','🎯'],[14,'delati — все формы','Настоящее и прошедшее','🛠️'],[15,'Аудирование','Распознаём знакомые фразы','🎧'],[16,'Глагол iti','grem / greš / gre','🚶'],[17,'Повелительное наклонение','biti, delati, iti + ne','📣'],[18,'Сравнение прилагательных','-ši, bolj/najbolj, исключения','📈']];
const words=[
['živjo','привет','приветствие','','Živjo, kako si?'],['dober dan','добрый день','приветствие','','Dober dan!'],['hvala','спасибо','приветствие','','Hvala lepa.'],['prosim','пожалуйста','приветствие','','Prosim, sedite.'],['nasvidenje','до свидания','приветствие','','Nasvidenje jutri.'],
['jaz','я','местоимение','','Jaz sem doma.'],['ti','ты','местоимение','','Ti si doma.'],['midva','мы двое','местоимение','dvojina, м./смеш.','Midva sva doma.'],['medve','мы две','местоимение','dvojina, ж.','Medve sva sestri.'],['vidva','вы двое','местоимение','dvojina, м./смеш.','Vidva sta tukaj.'],['vedve','вы две','местоимение','dvojina, ж.','Vedve sta doma.'],['onadva','они двое','местоимение','dvojina','Onadva sta brata.'],['onidve','они две','местоимение','dvojina','Onidve sta sestri.'],
['ena','одна','число','','Ena kava.'],['dva','два','число','м.р.','Dva brata.'],['dve','две','число','ж./ср.р.','Dve sestri.'],['tri','три','число','','Tri knjige.'],['štiri','четыре','число','','Štiri hiše.'],['pet','пять','число','','Pet dni.'],
['mama','мама','семья','ж.р.','Moja mama je doma.'],['oče','папа','семья','м.р.','Moj oče dela.'],['brat','брат','семья','м.р.','Imam brata.'],['sestra','сестра','семья','ж.р.','Imam sestro.'],
['voda','вода','еда','ж.р.','Pijem vodo.'],['kava','кофе','еда','ж.р.','Pijem kavo.'],['čaj','чай','еда','м.р.','Čaj je vroč.'],['kruh','хлеб','еда','м.р.','Kruh je svež.'],['sir','сыр','еда','м.р.','Rad imam sir.'],['mleko','молоко','еда','ср.р.','Mleko je hladno.'],
['danes','сегодня','календарь','','Danes sem doma.'],['jutri','завтра','календарь','','Jutri grem v Ljubljano.'],['včeraj','вчера','календарь','','Včeraj sem delal.'],['ponedeljek','понедельник','календарь','','Danes je ponedeljek.'],['petek','пятница','календарь','','V petek gremo ven.'],
['biti','быть','глагол','','Jaz sem doma.'],['imeti','иметь','глагол','','Imam avto.'],['hoteti','хотеть','глагол','','Hočem kavo.'],['delati','делать / работать','глагол','','Danes delam.'],['iti','идти / ехать','глагол','','Grem domov.'],['jesti','есть','глагол','','Jem kruh.'],['piti','пить','глагол','','Pijem vodo.'],['živeti','жить','глагол','','Živim v Sloveniji.'],['govoriti','говорить','глагол','','Govorim rusko.'],['razumeti','понимать','глагол','','Razumem malo.'],['videti','видеть','глагол','','Vidim hišo.'],['vedeti','знать','глагол','','Ne vem.'],['dati','дать','глагол','','Dam ti knjigo.'],['vzeti','взять','глагол','','Vzamem vodo.'],['priti','прийти','глагол','','Pridem jutri.'],['spati','спать','глагол','','Spim doma.'],['brati','читать','глагол','','Berem knjigo.'],['pisati','писать','глагол','','Pišem sporočilo.'],['kupiti','купить','глагол','','Kupim kruh.'],['učiti se','учиться','глагол','','Učim se slovensko.'],
['rdeč','красный','цвет','м.р.; rdeča/rdeče','Rdeč avto.'],['moder','синий','цвет','m.; modra/modro','Moder avto.'],['zelen','зелёный','цвет','m.; zelena/zeleno','Zelen čaj.'],['dober','хороший','прилагательное','boljši','Dober dan.'],['velik','большой','прилагательное','večji','Velik dom.'],['majhen','маленький','прилагательное','manjši','Majhen pes.'],
['hiša','дом','дом','ж.р.','To je hiša.'],['stanovanje','квартира','дом','ср.р.','Stanovanje je majhno.'],['miza','стол','дом','ж.р.','Knjiga je na mizi.'],['okno','окно','дом','ср.р.','Okno je odprto.'],
['kaj','что','вопрос','','Kaj je to?'],['kdo','кто','вопрос','','Kdo je to?'],['kje','где','вопрос','','Kje si?'],['kdaj','когда','вопрос','','Kdaj prideš?'],['zakaj','почему','вопрос','','Zakaj?'],['kako','как','вопрос','','Kako si?'],['koliko','сколько','вопрос','','Koliko stane?']
].map((x,i)=>({id:i,sl:x[0],ru:x[1],cat:x[2],meta:x[3],example:x[4],level:'A0'}));
const mc=(q,c,a)=>({type:'mc',q,choices:c,answer:a}),fill=(q,c,a)=>({type:'fill',q,choices:c,answer:a}),build=(q,a,t)=>({type:'build',q,answer:a,tiles:t}),order=(q,t)=>({type:'order',q,tiles:t,answer:t.join(' ')}),listen=(q,text,c,a)=>({type:'listen',q,text,choices:c,answer:a}),match=(q,p)=>({type:'match',q,pairs:p,answer:'все пары'});
const ex={
1:[mc('Как сказать «привет»?',['živjo','hvala','nasvidenje'],'živjo'),build('Соберите hvala','hvala',['h','v','a','l','a'])],
2:[mc('«два» с мужским родом',['dva','dve','tri'],'dva'),fill('Midva ___ doma.',['sva','sta','smo'],'sva')],3:[mc('sestra =',['сестра','мама','брат'],'сестра'),order('«У меня есть брат»',['Imam','brata','.'])],4:[mc('voda =',['вода','кофе','чай'],'вода'),order('«Я пью кофе»',['Pijem','kavo','.'])],5:[mc('«сегодня» =',['danes','jutri','včeraj'],'danes'),fill('Danes je ___.',['ponedeljek','mleko','sestra'],'ponedeljek')],6:[fill('Jaz ___ Aleks.',['sem','si','je'],'sem'),mc('Ona ___ doma.',['je','sem','so'],'je')],7:[fill('Jaz ___ avto.',['imam','imaš','ima'],'imam'),order('«У нас есть дом»',['Mi','imamo','hišo','.'])],8:[mc('Женская форма rdeč',['rdeča','rdeče','rdeči'],'rdeča'),fill('To je ___ hiša.',['velika','velik','veliko'],'velika')],9:[mc('okno =',['окно','дверь','стол'],'окно'),order('«Окно открыто»',['Okno','je','odprto','.'])],10:[match('Соедините пары',[['kaj','что'],['kdo','кто'],['kje','где']]),mc('«Где ты?»',['Kje si?','Kako si?','Kdo si?'],'Kje si?')],11:[fill('Midva ___ doma.',['sva','sta','smo'],'sva'),mc('l-причастие biti, м.р.',['bil','bila','bilo'],'bil')],12:[fill('Vidva ___ čas.',['imata','imava','imate'],'imata'),mc('«Мы имеем»',['imamo','imata','imam'],'imamo')],13:[fill('Jaz ___ kavo.',['hočem','hočeš','hoče'],'hočem'),mc('«Они хотят»',['hočejo','hočemo','hočeta'],'hočejo')],14:[fill('Midva ___ skupaj.',['delava','delata','delamo'],'delava'),mc('«Я работал» (м.р.)',['delal sem','delala sem','delali smo'],'delal sem')],15:[listen('Прослушайте фразу','Dober dan',['Dober dan','Hvala','Nasvidenje'],'Dober dan'),listen('Прослушайте слово','voda',['voda','kava','kruh'],'voda')],16:[fill('Jaz ___ domov.',['grem','greš','gre'],'grem'),mc('«мы идём»',['gremo','greva','gredo'],'gremo'),mc('l-причастие iti, ж.р.',['šla','šel','šlo'],'šla')],17:[mc('Повелительное iti, 2 ед.',['pojdi','grem','iti'],'pojdi'),mc('«не работай»',['ne delaj','ne delaš','ni delaj'],'ne delaj')],18:[mc('dober →',['boljši','večji','dobrši'],'boljši'),mc('velik →',['večji','boljši','manjši'],'večji'),fill('___ zanimiv',['bolj','naj','več'],'bolj')]};
const verb={biti:['sem','si','je','sva','sta','sta','smo','ste','so'],imeti:['imam','imaš','ima','imava','imata','imata','imamo','imate','imajo'],hoteti:['hočem','hočeš','hoče','hočeva','hočeta','hočeta','hočemo','hočete','hočejo'],delati:['delam','delaš','dela','delava','delata','delata','delamo','delate','delajo'],iti:['grem','greš','gre','greva','gresta','gresta','gremo','greste','gredo']};
const persons=['jaz','ti','on/ona','midva/medve','vidva/vedve','onadva/onidve','mi','vi','oni/one'];
